# .yarnrc.yml

yarnPath: .yarn/releases/yarn-1.22.22.cjs
enableImmutableInstalls: false

# Disable lockfile integrity enforcement (Classic only)
enableImmutableInstalls: false

# Secure HTTPS requests
enableStrictSsl: true

# Use project-specific cache instead of global
cacheFolder: .yarn/cache
enableGlobalCache: false

# Prefer local cache (helps in CI/CD)
preferOffline: true

# Enable workspaces even without root package.json
workspaces-experimental: true
