# .yarnrc.yml
yarnPath: .yarn/releases/yarn-1.22.22.cjs

enableImmutableInstalls: false
enableStrictSsl: true

# Offline mirror support (optional)
cacheFolder: .yarn/cache
enableGlobalCache: false

# Enables zero-installs (if committed node_modules/.yarn/cache is present)
preferOffline: true
