# netlify.toml

[build]
  base   = "frontend"
  command = "npm run build"
  publish = "frontend/web-build"

[dev]
  # if you use Netlify Dev locally
  framework = "none"

[[redirects]]
  from = "/api/*"
  to   = "https://aetherionai-mobile.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
