{
  "name": "aetherion-mobile",
  "version": "1.0.0",
  "private": true,
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "build": "expo export --platform web",
    "check:secrets": "bash security-check.sh",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "format": "prettier --write .",
    "prepare": "husky install"
  },
  "dependencies": {
    "expo": "49.0.13",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.0",
    "react-native-web": "~0.19.6",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.6.1",
    "react-native-safe-area-context": "^4.8.1",
    "react-native-screens": "^3.30.0",
    "@expo/metro-runtime": "~3.1.3",
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/stack": "^6.4.1",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "discord.js": "^14.14.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.20",
    "@babel/preset-env": "^7.22.20",
    "@react-native/babel-preset": "^8.5.0",
    "eslint": "^8.56.0",
    "prettier": "^3.2.5",
    "husky": "^8.0.3",
    "lint-staged": "^15.2.0"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": ["eslint --fix", "prettier --write"]
  },
  "engines": {
    "node": "18.x",
    "npm": ">=9.0.0"
  }
}
