# ┌────────────────────────────────────────────────────────┐
# │  netlify.toml (located at the repo root)              │
# └────────────────────────────────────────────────────────┘

[build]
  # “base” = where Netlify will cd into before running npm
  base    = "frontend"
  # run install + build
  command = "npm install && npm run build"
  # where to look for the compiled web output
  publish = "frontend/web-build"

[[redirects]]
  from   = "/api/*"
  to     = "https://aetherion-mobile.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
