# ─────────────────────────────────────────────────────────
# Netlify configuration (placed at the project root)
# ─────────────────────────────────────────────────────────

[build]
  base    = "frontend"
  command = "expo export"
  publish = "web-build"

[[redirects]]
  from    = "/api/*"
  to      = "https://aetherion-mobile.onrender.com/api/:splat"
  status  = 200

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
