[build]
base = "apps/aetherion-mobile"
command = "npm install --legacy-peer-deps && npm run build"
publish = "apps/aetherion-mobile/dist"

[build.environment]
NODE_VERSION = "18.20.3"
YARN_VERSION = "1.22.22"
EXPO_PUBLIC_API_URL = "https://your-api-domain.com"
CI = "false"  # avoids certain CI-specific Expo issues

[context.production.environment]
EXPO_PUBLIC_API_URL = "https://your-api-domain.com"

[context.deploy-preview.environment]
EXPO_PUBLIC_API_URL = "https://your-preview-api-domain.com"

[context.branch-deploy.environment]
EXPO_PUBLIC_API_URL = "https://your-branch-api-domain.com"

[dev]
command = "expo start --web"
port = 8888
targetPort = 19006
framework = "#custom"
autoLaunch = false
