[build]
  base    = "frontend"
  command = "npm run build"
  publish = "web-build"

[context.production.environment]
  NODE_VERSION        = "18"
  EXPO_PUBLIC_API_URL = "https://<https://aetherionai-mobile.onrender.com>"

[[redirects]]
  from   = "/api/*"
  to     = "https://<https://aetherionai-mobile.onrender.com>/api/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
