[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/web-build"

[context.production.environment]
  NODE_VERSION = "18"
  EXPO_PUBLIC_API_URL = "https://aetherion-mobile.onrender.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://aetherion-mobile.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
