[build]
base = "apps/aetherion-mobile"
publish = "apps/aetherion-mobile/dist"
command = "yarn install --legacy-peer-deps && expo export --platform web"

[build.environment]
NODE_VERSION = "18.20.3"
YARN_VERSION = "1.22.22"
EXPO_PUBLIC_API_URL = "https://your-api.example.com" # <-- replace this if needed

[dev]
command = "expo start --web"
targetPort = 19006
