[build]
base = "apps/aetherion-mobile"
publish = "dist"
command = "yarn install && yarn build"

[build.environment]
NODE_VERSION = "18"
YARN_VERSION = "1.22.22"
EXPO_PUBLIC_API_URL = "https://your-backend-api-url"
