[build]
base = "apps/aetherion-mobile"
command = "yarn install && yarn build"
publish = "apps/aetherion-mobile/dist"

[build.environment]
NODE_VERSION = "18.20.3"
YARN_VERSION = "1.22.22"
EXPO_PUBLIC_API_URL = "https://aetherionai-mobile.onrender.com"
CI = "true"
NPM_CONFIG_WORKSPACES = "false"
NPM_FLAGS = "--legacy-peer-deps"

[context.production.environment]
EXPO_PUBLIC_API_URL = "https://aetherionai-mobile.onrender.com"

[context.deploy-preview.environment]
EXPO_PUBLIC_API_URL = "https://aetherionai-mobile.onrender.com"

[context.branch-deploy.environment]
EXPO_PUBLIC_API_URL = "https://aetherionai-mobile.onrender.com"

[dev]
command = "expo start --web"
port = 8888
targetPort = 19006
framework = "#custom"
autoLaunch = false
