[build]
base = "apps/aetherion-mobile"
publish = "apps/aetherion-mobile/dist"
command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
NODE_VERSION = "18.20.8"
NPM_FLAGS = "--legacy-peer-deps"
EXPO_PUBLIC_API_URL = "https://aetherionai-mobile.onrender.com"

[context.production.environment]
EXPO_PUBLIC_API_URL = "https://aetherionai-mobile.onrender.com"

[context.deploy-preview.environment]
EXPO_PUBLIC_API_URL = "https://preview.aetherionai-mobile.onrender.com"

[context.branch-deploy.environment]
EXPO_PUBLIC_API_URL = "https://branch.aetherionai-mobile.onrender.com"

[dev]
command = "npx expo start --web"
port = 8888
targetPort = 19006
framework = "#custom"
autoLaunch = false
