[build]
base = "apps/aetherion-mobile"
publish = "apps/aetherion-mobile/dist"
command = "./setup.sh && yarn build"

[build.environment]
NODE_VERSION = "18"
YARN_VERSION = "1.22.22"
EXPO_PUBLIC_API_URL = "https://aetherionai-api.onrender.com"

[[plugins]]
package = "@netlify/plugin-nextjs"
