[build]
base = "apps/aetherion-mobile"
command = "npm install --legacy-peer-deps && expo export --platform web"
publish = "apps/aetherion-mobile/dist"
node_version = "18.20.3"

[context.production.environment]
EXPO_PUBLIC_API_URL = "https://your-api-domain.com"

[context.deploy-preview.environment]
EXPO_PUBLIC_API_URL = "https://your-preview-api-domain.com"

[context.branch-deploy.environment]
EXPO_PUBLIC_API_URL = "https://your-branch-api-domain.com"

[dev]
command = "expo start"
targetPort = 8081
port = 8888
framework = "#custom"
autoLaunch = false
