# Root Netlify config
[build]
base = "apps/aetherion-mobile"
publish = "apps/aetherion-mobile/dist"
command = "npm install --legacy-peer-deps && npx expo export --platform web"

[build.environment]
NODE_VERSION = "18.20.8"
YARN_VERSION = "1.22.22"
EXPO_PUBLIC_API_URL = "https://your-api.example.com"

[dev]
command = "expo start --web"
targetPort = 19006
