[build]
  command = "npm run build"
  publish = "frontend/web-build"
  base = "frontend"

[build.environment]
  EXPO_PUBLIC_API_URL = "https://aetherionai.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://aetherionai.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
