[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from   = "/api/*"
  to     = "https://aetherion-mobile.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
