# netlify.toml (at the root of your Git repo)

[build]
  base    = "frontend"
  command = "npm run build"
  publish = "web-build"

[[redirects]]
  from    = "/api/*"
  to      = "https://aetherion-mobile.onrender.com/api/:splat"
  status  = 200

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
