[build]
  base = "apps/aetherion-mobile"
  command = "yarn install && expo export"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  EXPO_PUBLIC_API_URL = "https://aetherionai-api.onrender.com"
