[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I", "B", "C90", "N", "UP", "SIM", "ARG", "RUF"]
ignore = ["E501", "B008"]
exclude = [
  "migrations",
  "__pycache__",
  ".venv",
  "tests",
  "env",
  "venv",
  ".git",
  ".github"
]
