[tool.ruff]
line-length = 100               # Matches modern readability conventions
target-version = "py310"        # Aligns with your Python 3.10 usage

# Enable these useful rule sets
select = ["E", "F", "I", "B", "C90", "N", "UP", "SIM", "ARG", "RUF"]

# Ignore long lines and B008 (function defaults to mutable types)
ignore = ["E501", "B008"]

# Ignore common non-source directories
exclude = [
  "migrations",
  "__pycache__",
  ".venv",
  "tests",       # If you lint tests later, remove this
  "env",
  "venv",
  ".git",
  ".github"
]
