[tool.ruff]
line-length = 100
target-version = "py310"

select = [
  "E",    # pycodestyle
  "F",    # pyflakes
  "I",    # isort
  "B",    # bugbear
  "C90",  # mccabe complexity
  "N",    # pep8-naming
  "UP",   # pyupgrade
  "SIM",  # simplify
  "ARG",  # unused arguments
  "RUF"   # ruff-specific rules
]

ignore = [
  "E501",  # line too long
  "B008"   # function call as default arg
]

exclude = [
  "migrations",
  "__pycache__",
  ".venv",
  "tests",
  "env",
  "venv",
  ".git",
  ".github"
]
