services:
  - type: web
    name: aetherion-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    buildFilter:
      paths:
        - services/backend/**/*
    buildDirectory: services/backend
