# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn Classic
        run: |
          mkdir -p .yarn/releases
          curl -L https://classic.yarnpkg.com/latest.tar.gz | tar xz -C .yarn/releases --strip-components=1
          echo "$(pwd)/.yarn/releases" >> $GITHUB_PATH

      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            apps/aetherion-mobile/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install frontend dependencies
        working-directory: apps/aetherion-mobile
        run: yarn install --frozen-lockfile

      - name: Lint frontend
        working-directory: apps/aetherion-mobile
        run: yarn lint

      - name: Format check
        working-directory: apps/aetherion-mobile
        run: yarn format --check

      - name: Setup Python backend and install dependencies
        working-directory: services/backend
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend security check
        working-directory: services/backend
        run: bash security-check.sh
